---

# docker driver configuration (CI)
docker:
  containers:
    - name: gitea-centos-7
      image: atosatto/centos
      image_version: 7-systemd
      privileged: True
    - name: gitea-ubuntu-16.04
      image: atosatto/ubuntu
      image_version: 16.04
      privileged: True
    - name: gitea-ubuntu-14.04
      image: ubuntu
      image_version: 14.04
      privileged: True
    # Unfortunately, upstart does not run in Docker containers,
    # so no Ubuntu 14.04 docker tests :/

# vagrant driver configuration (development)
vagrant:
  platforms:
    - name: centos-7
      box: centos/7
    - name: ubuntu-16.04
      box: bento/ubuntu-16.04
    - name: ubuntu-14.04
      box: bento/ubuntu-14.04
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 2048
        cpus: 2
  instances:
    - name: ansible-gitea-01
      interfaces:
        # network needed to connect
        - network_name: private_network
          type: dhcp
          auto_config: true
      options:
        append_platform_to_hostname: yes

verifier:
  name: testinfra
