---

# gitea download url
gitea_download_url: "https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-{{ ansible_system | lower }}-{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

# default init scripts location
initd_conf_dir: /etc/init.d

# python pip packages required to support SNI certificates
python_sni_pip_dependencies:
  - pyopenssl
  - ndg-httpsclient
  - pyasn1
